import {
  Customer,
  CustomerActivity,
  CustomerBooking,
  CustomerFormValues,
  CustomerKpis,
  CustomerReview,
  CustomerTransaction,
  JourneyStep,
} from "./types";

export const customerKpis: CustomerKpis = {
  total: 12,
  totalGrowth: 8.4,
  verified: 11,
  verifiedPercent: 92,
  active: 11,
  blocked: 1,
  newThisMonth: 2,
  newGrowth: 12.1,
};

export const cityOptions = [
  "Hyderabad",
  "Secunderabad",
  "Warangal",
  "Karimnagar",
  "Khammam",
  "Nizamabad",
  "Visakhapatnam",
  "Vijayawada",
  "Tirupati",
  "Guntur",
  "Rajahmundry",
  "Kakinada",
  "Bengaluru",
  "Mysuru",
  "Mangaluru",
  "Hubballi",
  "Chennai",
  "Coimbatore",
  "Madurai",
  "Tiruchirappalli",
];

function buildJourney(verified: boolean, hasBooking: boolean, hasReview: boolean): JourneyStep[] {
  return [
    { key: "registered", label: "Registered", status: "completed", date: "Jan 12, 2024" },
    {
      key: "verified",
      label: "Verified",
      status: verified ? "completed" : "current",
      date: verified ? "Jan 12, 2024" : undefined,
    },
    {
      key: "first_booking",
      label: "First Booking",
      status: hasBooking ? "completed" : verified ? "current" : "pending",
      date: hasBooking ? "Feb 03, 2024" : undefined,
    },
    {
      key: "upcoming",
      label: "Upcoming Event",
      status: hasBooking ? "completed" : "pending",
      date: hasBooking ? "Aug 12, 2026" : undefined,
    },
    {
      key: "completed",
      label: "Completed Event",
      status: hasBooking ? (hasReview ? "completed" : "current") : "pending",
      date: hasBooking ? "Jul 28, 2026" : undefined,
    },
    {
      key: "review",
      label: "Review Submitted",
      status: hasReview ? "completed" : hasBooking ? "current" : "pending",
      date: hasReview ? "Jul 29, 2026" : undefined,
    },
  ];
}

const sampleBookings: CustomerBooking[] = [
  {
    id: "1",
    bookingId: "BK-20481",
    venue: "The Grand Orchid, Hyderabad",
    eventType: "Wedding",
    bookingDate: "2026-06-12",
    eventDate: "2026-08-12",
    guests: 220,
    amount: 485000,
    paymentStatus: "paid",
    bookingStatus: "upcoming",
  },
  {
    id: "2",
    bookingId: "BK-20312",
    venue: "Skyline Rooftop, Bengaluru",
    eventType: "Corporate",
    bookingDate: "2026-05-02",
    eventDate: "2026-07-28",
    guests: 80,
    amount: 165000,
    paymentStatus: "paid",
    bookingStatus: "completed",
  },
  {
    id: "3",
    bookingId: "BK-20190",
    venue: "Harbor Banquet Hall, Chennai",
    eventType: "Birthday",
    bookingDate: "2026-03-18",
    eventDate: "2026-04-22",
    guests: 60,
    amount: 85000,
    paymentStatus: "refunded",
    bookingStatus: "cancelled",
  },
];

const sampleTransactions: CustomerTransaction[] = [
  {
    id: "1",
    transactionId: "TXN-98211",
    booking: "BK-20481",
    amount: 242500,
    method: "UPI",
    status: "success",
    date: "2026-06-12",
  },
  {
    id: "2",
    transactionId: "TXN-97102",
    booking: "BK-20312",
    amount: 165000,
    method: "UPI",
    status: "success",
    date: "2026-05-02",
  },
  {
    id: "3",
    transactionId: "TXN-96044",
    booking: "BK-20190",
    amount: 42500,
    method: "Card",
    status: "failed",
    date: "2026-03-18",
  },
];

const sampleReviews: CustomerReview[] = [
  {
    id: "1",
    venue: "Skyline Rooftop, Bengaluru",
    rating: 5,
    comment: "Flawless coordination and beautiful setup. Highly recommended.",
    date: "2026-07-29",
    reply: "Thank you for celebrating with us — we look forward to hosting you again.",
  },
  {
    id: "2",
    venue: "Harbor Banquet Hall, Chennai",
    rating: 4,
    comment: "Great service overall. Parking could be better.",
    date: "2026-04-25",
    reply: "Appreciate the feedback. We’ve expanded valet capacity for peak evenings.",
  },
];

const sampleActivities: CustomerActivity[] = [
  {
    id: "1",
    title: "Last Login",
    description: "Signed in from Hyderabad, India",
    date: "2026-07-30T09:24:00",
    type: "login",
  },
  {
    id: "2",
    title: "Review Submitted",
    description: "Left a 5-star review for Skyline Rooftop, Bengaluru",
    date: "2026-07-29T16:10:00",
    type: "review",
  },
  {
    id: "3",
    title: "Booking Completed",
    description: "Event BK-20312 marked as completed",
    date: "2026-07-28T21:00:00",
    type: "booking",
  },
  {
    id: "4",
    title: "Payment Received",
    description: "Advance payment of ₹2,42,500 for BK-20481",
    date: "2026-06-12T11:20:00",
    type: "payment",
  },
  {
    id: "5",
    title: "Email Verified",
    description: "Customer verified email address",
    date: "2024-01-12T10:05:00",
    type: "verify",
  },
  {
    id: "6",
    title: "Customer Registered",
    description: "Customer joined via Website",
    date: "2024-01-12T09:40:00",
    type: "register",
  },
];

function enrich(
  base: Omit<
    Customer,
    | "journey"
    | "recentBookings"
    | "recentInvoices"
    | "recentTransactions"
    | "recentReviews"
    | "activities"
    | "emailVerified"
    | "mobileVerified"
    | "communicationPreference"
    | "upcomingBookings"
    | "completedBookings"
    | "cancelledBookings"
    | "averageBooking"
    | "totalPaid"
    | "pendingPayments"
    | "refundedPayments"
    | "favoriteEventType"
    | "averageRating"
    | "country"
    | "createdBy"
    | "createdAt"
    | "updatedBy"
    | "updatedAt"
    | "version"
    | "gender"
    | "dob"
  > &
    Partial<Customer>
): Customer {
  const verified = base.verification === "verified";
  const hasBooking = (base.bookings || 0) > 0;
  const hasReview = (base.reviews || 0) > 0;

  return {
    country: "India",
    addressLine1: "",
    addressLine2: "",
    state: "",
    zipCode: "",
    gender: "prefer_not_to_say",
    dob: "",
    emailVerified: verified,
    mobileVerified: verified,
    communicationPreference: "email",
    upcomingBookings: base.upcomingBookings ?? 0,
    completedBookings: base.completedBookings ?? 0,
    cancelledBookings: base.cancelledBookings ?? 0,
    averageBooking: base.averageBooking ?? 0,
    totalPaid: base.totalPaid ?? 0,
    pendingPayments: base.pendingPayments ?? 0,
    refundedPayments: base.refundedPayments ?? 0,
    favoriteEventType: base.favoriteEventType ?? "—",
    averageRating: hasReview ? base.averageRating ?? 4.6 : 0,
    createdBy: "System",
    createdAt: base.registrationDate,
    updatedBy: "Admin User",
    updatedAt: base.lastLogin,
    version: "v1.0",
    journey: buildJourney(verified, hasBooking, hasReview),
    recentBookings: base.recentBookings ?? [],
    recentInvoices: base.recentInvoices ?? [],
    recentTransactions: base.recentTransactions ?? [],
    recentReviews: hasReview ? sampleReviews : [],
    activities: sampleActivities,
    ...base,
    bookings: base.bookings ?? 0,
    totalSpend: base.totalSpend ?? 0,
  } as Customer;
}

export const mockCustomers: Customer[] = [
  enrich({
    id: "1",
    customerId: "CUST-100124",
    name: "Rahul Sharma",
    email: "rahul.sharma@email.com",
    phone: "+91 98765 43210",
    city: "Hyderabad",
    gender: "male",
    dob: "1990-04-18",
    addressLine1: "14, Linking Road",
    addressLine2: "Bandra West",
    state: "Telangana",
    zipCode: "400050",
    initials: "RS",
    status: "active",
    verification: "verified",
    bookings: 14,
    totalSpend: 1845000,
    registrationDate: "2024-01-12",
    lastLogin: "2026-07-30T09:24:00",
    source: "website",
    memberSince: "Jan 2024",
    reviews: 8,
    lastBooking: "Jul 28, 2026",
    notes: "Prefers rooftop venues for corporate events.",
  }),
  enrich({
    id: "2",
    customerId: "CUST-100125",
    name: "Priya Patel",
    email: "priya.patel@email.com",
    phone: "+91 98201 55678",
    city: "Karimnagar",
    gender: "female",
    dob: "1992-09-03",
    addressLine1: "22, CG Road",
    state: "Telangana",
    zipCode: "380009",
    initials: "PP",
    status: "active",
    verification: "verified",
    bookings: 9,
    totalSpend: 1268000,
    registrationDate: "2024-03-04",
    lastLogin: "2026-07-29T18:10:00",
    source: "mobile_app",
    memberSince: "Mar 2024",
    reviews: 5,
    lastBooking: "Jul 20, 2026",
  }),
  enrich({
    id: "3",
    customerId: "CUST-100126",
    name: "Arjun Reddy",
    email: "arjun.reddy@email.com",
    phone: "+91 99860 11223",
    city: "Hyderabad",
    gender: "male",
    addressLine1: "Plot 8, Jubilee Hills",
    state: "Telangana",
    zipCode: "500033",
    initials: "AR",
    status: "pending",
    verification: "pending",
    bookings: 2,
    totalSpend: 240000,
    registrationDate: "2026-07-02",
    lastLogin: "2026-07-28T11:05:00",
    source: "referral",
    memberSince: "Jul 2026",
    reviews: 0,
    lastBooking: "Jul 15, 2026",
  }),
  enrich({
    id: "4",
    customerId: "CUST-100127",
    name: "Ananya Iyer",
    email: "ananya.iyer@email.com",
    phone: "+91 94440 77889",
    city: "Chennai",
    gender: "female",
    addressLine1: "7, T Nagar Main Road",
    state: "Tamil Nadu",
    zipCode: "600017",
    initials: "AI",
    status: "active",
    verification: "verified",
    bookings: 21,
    totalSpend: 3120000,
    registrationDate: "2023-11-18",
    lastLogin: "2026-07-30T07:40:00",
    source: "partner",
    memberSince: "Nov 2023",
    reviews: 14,
    lastBooking: "Jul 29, 2026",
  }),
  enrich({
    id: "5",
    customerId: "CUST-100128",
    name: "Vikram Singh",
    email: "vikram.singh@email.com",
    phone: "+91 98111 33445",
    city: "Hyderabad",
    gender: "male",
    addressLine1: "B-12, Connaught Place",
    state: "Hyderabad",
    zipCode: "110001",
    initials: "VS",
    status: "blocked",
    verification: "rejected",
    bookings: 1,
    totalSpend: 85000,
    registrationDate: "2025-09-09",
    lastLogin: "2026-05-12T14:20:00",
    source: "website",
    memberSince: "Sep 2025",
    reviews: 0,
  }),
  enrich({
    id: "6",
    customerId: "CUST-100129",
    name: "Sneha Nair",
    email: "sneha.nair@email.com",
    phone: "+91 98470 22334",
    city: "Madurai",
    gender: "female",
    addressLine1: "Marine Drive",
    state: "Tamil Nadu",
    zipCode: "682031",
    initials: "SN",
    status: "active",
    verification: "verified",
    bookings: 7,
    totalSpend: 945000,
    registrationDate: "2024-06-22",
    lastLogin: "2026-07-27T16:55:00",
    source: "mobile_app",
    memberSince: "Jun 2024",
    reviews: 3,
    lastBooking: "Jul 10, 2026",
  }),
  enrich({
    id: "7",
    customerId: "CUST-100130",
    name: "Rohan Mehta",
    email: "rohan.mehta@email.com",
    phone: "+91 98920 66778",
    city: "Bengaluru",
    gender: "male",
    addressLine1: "Baner Road",
    state: "Telangana",
    zipCode: "411045",
    initials: "RM",
    status: "inactive",
    verification: "verified",
    bookings: 4,
    totalSpend: 520000,
    registrationDate: "2024-08-14",
    lastLogin: "2026-03-01T10:12:00",
    source: "admin",
    memberSince: "Aug 2024",
    reviews: 2,
    lastBooking: "Feb 18, 2026",
  }),
  enrich({
    id: "8",
    customerId: "CUST-100131",
    name: "Kavya Rao",
    email: "kavya.rao@email.com",
    phone: "+91 99001 44556",
    city: "Bengaluru",
    gender: "female",
    addressLine1: "12th Main, Indiranagar",
    state: "Karnataka",
    zipCode: "560038",
    initials: "KR",
    status: "active",
    verification: "verified",
    bookings: 11,
    totalSpend: 1578000,
    registrationDate: "2024-02-28",
    lastLogin: "2026-07-30T12:01:00",
    source: "website",
    memberSince: "Feb 2024",
    reviews: 6,
    lastBooking: "Jul 26, 2026",
  }),
  enrich({
    id: "9",
    customerId: "CUST-100132",
    name: "Aman Gupta",
    email: "aman.gupta@email.com",
    phone: "+91 98180 99887",
    city: "Warangal",
    gender: "male",
    addressLine1: "C-Scheme",
    state: "Telangana",
    zipCode: "302001",
    initials: "AG",
    status: "active",
    verification: "pending",
    bookings: 3,
    totalSpend: 410000,
    registrationDate: "2026-06-11",
    lastLogin: "2026-07-25T20:30:00",
    source: "referral",
    memberSince: "Jun 2026",
    reviews: 1,
    lastBooking: "Jul 05, 2026",
  }),
  enrich({
    id: "10",
    customerId: "CUST-100133",
    name: "Meera Das",
    email: "meera.das@email.com",
    phone: "+91 98300 11220",
    city: "Chennai",
    gender: "female",
    addressLine1: "Park Street",
    state: "Tamil Nadu",
    zipCode: "700016",
    initials: "MD",
    status: "active",
    verification: "verified",
    bookings: 18,
    totalSpend: 2764000,
    registrationDate: "2023-12-05",
    lastLogin: "2026-07-29T22:15:00",
    source: "partner",
    memberSince: "Dec 2023",
    reviews: 11,
    lastBooking: "Jul 22, 2026",
  }),
  enrich({
    id: "11",
    customerId: "CUST-100134",
    name: "Aditya Kapoor",
    email: "aditya.kapoor@email.com",
    phone: "+91 98712 33440",
    city: "Hubballi",
    gender: "male",
    addressLine1: "Sector 17",
    state: "Hubballi",
    zipCode: "160017",
    initials: "AK",
    status: "pending",
    verification: "pending",
    bookings: 0,
    totalSpend: 0,
    registrationDate: "2026-07-28",
    lastLogin: "2026-07-28T08:00:00",
    source: "website",
    memberSince: "Jul 2026",
    reviews: 0,
  }),
  enrich({
    id: "12",
    customerId: "CUST-100135",
    name: "Neha Fernandes",
    email: "neha.fernandes@email.com",
    phone: "+91 98221 55660",
    city: "Visakhapatnam",
    gender: "female",
    addressLine1: "Calangute Beach Road",
    state: "Visakhapatnam",
    zipCode: "403516",
    initials: "NF",
    status: "active",
    verification: "verified",
    bookings: 6,
    totalSpend: 780000,
    registrationDate: "2025-01-19",
    lastLogin: "2026-07-26T13:45:00",
    source: "mobile_app",
    memberSince: "Jan 2025",
    reviews: 4,
    lastBooking: "Jul 12, 2026",
  }),
];

export function formatCurrency(amount: number) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatDate(date: string) {
  if (!date) return "—";
  return new Date(date).toLocaleDateString("en-IN", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

export function formatDateTime(date: string) {
  if (!date) return "—";
  return new Date(date).toLocaleString("en-IN", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

export function getCustomerById(id: string) {
  return mockCustomers.find((c) => c.id === id || c.customerId === id);
}

export function customerToFormValues(customer: Customer): CustomerFormValues {
  return {
    name: customer.name,
    email: customer.email,
    phone: customer.phone,
    gender: customer.gender || "",
    city: customer.city,
    country: customer.country,
    addressLine1: customer.addressLine1 || "",
    addressLine2: customer.addressLine2 || "",
    state: customer.state || "",
    zipCode: customer.zipCode || "",
    dob: customer.dob || "",
    source: customer.source,
    status: customer.status,
    emailVerified: customer.emailVerified,
    mobileVerified: customer.mobileVerified,
    communicationPreference: customer.communicationPreference,
    verification: customer.verification,
    notes: customer.notes || "",
  };
}

export const emptyCustomerForm: CustomerFormValues = {
  name: "",
  email: "",
  phone: "",
  gender: "",
  city: "",
  country: "India",
  addressLine1: "",
  addressLine2: "",
  state: "",
  zipCode: "",
  dob: "",
  source: "admin",
  status: "pending",
  emailVerified: false,
  mobileVerified: false,
  communicationPreference: "email",
  verification: "pending",
  notes: "",
};

/** Blank customer shell for Create / Clone — same shape as view/edit. */
export function blankCustomer(overrides: Partial<Customer> = {}): Customer {
  const now = new Date().toISOString();
  return {
    id: "new",
    customerId: "CUST-NEW",
    name: "",
    email: "",
    phone: "",
    city: "",
    country: "India",
    addressLine1: "",
    addressLine2: "",
    state: "",
    zipCode: "",
    initials: "NC",
    status: "pending",
    verification: "pending",
    emailVerified: false,
    mobileVerified: false,
    communicationPreference: "email",
    bookings: 0,
    upcomingBookings: 0,
    completedBookings: 0,
    cancelledBookings: 0,
    totalSpend: 0,
    averageBooking: 0,
    totalPaid: 0,
    pendingPayments: 0,
    refundedPayments: 0,
    favoriteEventType: "—",
    averageRating: 0,
    registrationDate: now.slice(0, 10),
    lastLogin: "",
    source: "admin",
    notes: "",
    memberSince: "—",
    reviews: 0,
    lastBooking: "",
    createdBy: "—",
    createdAt: "",
    updatedBy: "—",
    updatedAt: "",
    version: "—",
    journey: [],
    recentBookings: [],
    recentInvoices: [],
    recentTransactions: [],
    recentReviews: [],
    activities: [],
    ...overrides,
  };
}
